[project]
name = "ragu-lm-docker-service"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.0",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.37.0",
    "vllm>=0.11.0",
]
